name: OPList
main: cn.mcsfs.oPList.OPList
version: 1.2.0
api-version: "1.12"  # 最低支持版本
commands:
  oplist:
    description: 重载插件配置
    usage: /<command> reload
    permission: oplist.reload
permissions:
  oplist.reload:
    description: 允许重载插件配置
    default: op
