name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # 必须要有写packages的权限

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github  # 必须与pom.xml中的repository id一致
        settings-path: ${{ github.workspace }}  # 自动生成Maven配置

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build and Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动注入的token
      run: |
        ./gradlew build publish  # 同时执行构建和发布

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/libs/*.jar
        retention-days: 7
